version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: arrival_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: arrival_db
    ports:
      - "5432:5432" # Expõe a porta para localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: